/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import javax.swing.JOptionPane;
import global.Global;
import javax.swing.ImageIcon;
import patollimaster.Dado;

/**
 *
 * @author Alan Acatictla M.
 */
public class Tablero extends javax.swing.JFrame {

    Dado dado = new Dado();

    /**
     * Creates new form Tablero
     */
    public Tablero() {
        initComponents();
        this.panelPlayer1.setVisible(false);
        this.panelPlayer2.setVisible(false);
        this.panelPlayer3.setVisible(false);
        this.panelPlayer4.setVisible(false);

        this.panelPlayer1.setVisible(true);
        this.labelPlayer1.setText(Global.jugadores.get(0).getNombre());
        this.Avatar1.setIcon(new ImageIcon(this.getClass().getResource("/Imagenes/" + Global.jugadores.get(0).getRutaAvatar())));

        this.panelPlayer2.setVisible(true);
        this.labelPlayer2.setText(Global.jugadores.get(1).getNombre());
        this.Avatar2.setIcon(new ImageIcon(this.getClass().getResource("/Imagenes/" + Global.jugadores.get(1).getRutaAvatar())));

        this.panelPlayer3.setVisible(true);
        this.labelPlayer3.setText(Global.jugadores.get(2).getNombre());
        this.Avatar3.setIcon(new ImageIcon(this.getClass().getResource("/Imagenes/" + Global.jugadores.get(2).getRutaAvatar())));

        this.panelPlayer4.setVisible(true);
        this.labelPlayer4.setText(Global.jugadores.get(3).getNombre());
        this.Avatar4.setIcon(new ImageIcon(this.getClass().getResource("/Imagenes/" + Global.jugadores.get(3).getRutaAvatar())));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelPlayer1 = new javax.swing.JPanel();
        Avatar1 = new javax.swing.JLabel();
        labelPlayer1 = new javax.swing.JLabel();
        panelPlayer2 = new javax.swing.JPanel();
        Avatar2 = new javax.swing.JLabel();
        labelPlayer2 = new javax.swing.JLabel();
        panelPlayer3 = new javax.swing.JPanel();
        Avatar3 = new javax.swing.JLabel();
        labelPlayer3 = new javax.swing.JLabel();
        panelPlayer4 = new javax.swing.JPanel();
        Avatar4 = new javax.swing.JLabel();
        labelPlayer4 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JPanel();
        txtSalir = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        tableroFondo = new javax.swing.JLabel();
        apostar25 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        apostar5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        apostar10 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        apostar50 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        apostar100 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btnPasar = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnTirarDados = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(2000, 1400));
        setMinimumSize(new java.awt.Dimension(2000, 1400));
        setPreferredSize(new java.awt.Dimension(2000, 1400));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        Avatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/avatar1.PNG"))); // NOI18N
        Avatar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Avatar1MouseClicked(evt);
            }
        });

        labelPlayer1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        labelPlayer1.setText("Jugador 1");

        javax.swing.GroupLayout panelPlayer1Layout = new javax.swing.GroupLayout(panelPlayer1);
        panelPlayer1.setLayout(panelPlayer1Layout);
        panelPlayer1Layout.setHorizontalGroup(
            panelPlayer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlayer1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Avatar1)
                .addGap(18, 18, 18)
                .addComponent(labelPlayer1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPlayer1Layout.setVerticalGroup(
            panelPlayer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlayer1Layout.createSequentialGroup()
                .addGroup(panelPlayer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPlayer1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Avatar1))
                    .addGroup(panelPlayer1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(labelPlayer1)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        Avatar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/avatar2.PNG"))); // NOI18N
        Avatar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Avatar2MouseClicked(evt);
            }
        });

        labelPlayer2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        labelPlayer2.setText("Jugador 2");

        javax.swing.GroupLayout panelPlayer2Layout = new javax.swing.GroupLayout(panelPlayer2);
        panelPlayer2.setLayout(panelPlayer2Layout);
        panelPlayer2Layout.setHorizontalGroup(
            panelPlayer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlayer2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Avatar2)
                .addGap(18, 18, 18)
                .addComponent(labelPlayer2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPlayer2Layout.setVerticalGroup(
            panelPlayer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlayer2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPlayer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Avatar2)
                    .addGroup(panelPlayer2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(labelPlayer2)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        Avatar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/avatar3.PNG"))); // NOI18N
        Avatar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Avatar3MouseClicked(evt);
            }
        });

        labelPlayer3.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        labelPlayer3.setText("Jugador 3");

        javax.swing.GroupLayout panelPlayer3Layout = new javax.swing.GroupLayout(panelPlayer3);
        panelPlayer3.setLayout(panelPlayer3Layout);
        panelPlayer3Layout.setHorizontalGroup(
            panelPlayer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlayer3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Avatar3)
                .addGap(18, 18, 18)
                .addComponent(labelPlayer3)
                .addContainerGap(202, Short.MAX_VALUE))
        );
        panelPlayer3Layout.setVerticalGroup(
            panelPlayer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlayer3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPlayer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Avatar3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPlayer3Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(labelPlayer3)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        Avatar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/avatar4.PNG"))); // NOI18N

        labelPlayer4.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        labelPlayer4.setText("jugador 4");

        javax.swing.GroupLayout panelPlayer4Layout = new javax.swing.GroupLayout(panelPlayer4);
        panelPlayer4.setLayout(panelPlayer4Layout);
        panelPlayer4Layout.setHorizontalGroup(
            panelPlayer4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlayer4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Avatar4)
                .addGap(18, 18, 18)
                .addComponent(labelPlayer4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPlayer4Layout.setVerticalGroup(
            panelPlayer4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlayer4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPlayer4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Avatar4)
                    .addGroup(panelPlayer4Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(labelPlayer4)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        btnSalir.setBackground(new java.awt.Color(212, 90, 90));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });

        txtSalir.setBackground(new java.awt.Color(255, 255, 255));
        txtSalir.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        txtSalir.setForeground(new java.awt.Color(255, 255, 255));
        txtSalir.setText("SALIR");
        txtSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnSalirLayout = new javax.swing.GroupLayout(btnSalir);
        btnSalir.setLayout(btnSalirLayout);
        btnSalirLayout.setHorizontalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSalirLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(txtSalir)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        btnSalirLayout.setVerticalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSalirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPlayer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPlayer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPlayer3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPlayer4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(panelPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(panelPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(panelPlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(panelPlayer4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 610, 1440);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        tableroFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImgTableroFondo.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(tableroFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 1011, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableroFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1120, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel10);
        jPanel10.setBounds(610, 0, 1400, 1120);

        apostar25.setBackground(new java.awt.Color(247, 226, 72));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("25");

        javax.swing.GroupLayout apostar25Layout = new javax.swing.GroupLayout(apostar25);
        apostar25.setLayout(apostar25Layout);
        apostar25Layout.setHorizontalGroup(
            apostar25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
            .addGroup(apostar25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(apostar25Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel16)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        apostar25Layout.setVerticalGroup(
            apostar25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(apostar25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(apostar25Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel16)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(apostar25);
        apostar25.setBounds(1050, 1240, 260, 70);

        apostar5.setBackground(new java.awt.Color(133, 214, 56));
        apostar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apostar5MouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("5");

        javax.swing.GroupLayout apostar5Layout = new javax.swing.GroupLayout(apostar5);
        apostar5.setLayout(apostar5Layout);
        apostar5Layout.setHorizontalGroup(
            apostar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
            .addGroup(apostar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(apostar5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel15)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        apostar5Layout.setVerticalGroup(
            apostar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(apostar5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(apostar5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel15)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(apostar5);
        apostar5.setBounds(1050, 1150, 260, 70);

        apostar10.setBackground(new java.awt.Color(175, 221, 42));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("10");

        javax.swing.GroupLayout apostar10Layout = new javax.swing.GroupLayout(apostar10);
        apostar10.setLayout(apostar10Layout);
        apostar10Layout.setHorizontalGroup(
            apostar10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
            .addGroup(apostar10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(apostar10Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel17)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        apostar10Layout.setVerticalGroup(
            apostar10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(apostar10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(apostar10Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel17)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(apostar10);
        apostar10.setBounds(1680, 1150, 260, 70);

        apostar50.setBackground(new java.awt.Color(244, 160, 8));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("50");

        javax.swing.GroupLayout apostar50Layout = new javax.swing.GroupLayout(apostar50);
        apostar50.setLayout(apostar50Layout);
        apostar50Layout.setHorizontalGroup(
            apostar50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
            .addGroup(apostar50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(apostar50Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel18)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        apostar50Layout.setVerticalGroup(
            apostar50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(apostar50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(apostar50Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel18)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(apostar50);
        apostar50.setBounds(1680, 1240, 260, 70);

        apostar100.setBackground(new java.awt.Color(255, 102, 102));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("100");

        javax.swing.GroupLayout apostar100Layout = new javax.swing.GroupLayout(apostar100);
        apostar100.setLayout(apostar100Layout);
        apostar100Layout.setHorizontalGroup(
            apostar100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
            .addGroup(apostar100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(apostar100Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel19)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        apostar100Layout.setVerticalGroup(
            apostar100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(apostar100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(apostar100Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel19)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(apostar100);
        apostar100.setBounds(1350, 1200, 290, 70);

        btnPasar.setBackground(new java.awt.Color(142, 142, 142));
        btnPasar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPasarMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("PASAR");

        javax.swing.GroupLayout btnPasarLayout = new javax.swing.GroupLayout(btnPasar);
        btnPasar.setLayout(btnPasarLayout);
        btnPasarLayout.setHorizontalGroup(
            btnPasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPasarLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel13)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        btnPasarLayout.setVerticalGroup(
            btnPasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPasarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(btnPasar);
        btnPasar.setBounds(650, 1240, 310, 80);

        btnTirarDados.setBackground(new java.awt.Color(13, 134, 201));
        btnTirarDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTirarDadosMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("TIRAR DADOS");

        javax.swing.GroupLayout btnTirarDadosLayout = new javax.swing.GroupLayout(btnTirarDados);
        btnTirarDados.setLayout(btnTirarDadosLayout);
        btnTirarDadosLayout.setHorizontalGroup(
            btnTirarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnTirarDadosLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(58, 58, 58))
        );
        btnTirarDadosLayout.setVerticalGroup(
            btnTirarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTirarDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(btnTirarDados);
        btnTirarDados.setBounds(650, 1140, 310, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseClicked
        // TODO add your handling code here:

        int confirm = JOptionPane.showConfirmDialog(this, "¿Seguro que quiere cerrar el juego?", "Confirmación", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_txtSalirMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnTirarDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTirarDadosMouseClicked
        // TODO add your handling code here:

        dado.tirarDado();
    }//GEN-LAST:event_btnTirarDadosMouseClicked

    private void btnPasarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPasarMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnPasarMouseClicked

    private void apostar5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apostar5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_apostar5MouseClicked

    private void Avatar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Avatar1MouseClicked
        // TODO add your handling code here:
        // establecerAvatar((ImageIcon) Avatar1.getIcon(), "avatar1.png");
    }//GEN-LAST:event_Avatar1MouseClicked

    private void Avatar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Avatar2MouseClicked
        // TODO add your handling code here:
        //establecerAvatar((ImageIcon) Avatar2.getIcon(), "avatar2.png");
    }//GEN-LAST:event_Avatar2MouseClicked

    private void Avatar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Avatar3MouseClicked
        // TODO add your handling code here:
        // establecerAvatar((ImageIcon) Avatar3.getIcon(), "avatar3.png");
    }//GEN-LAST:event_Avatar3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Avatar1;
    private javax.swing.JLabel Avatar2;
    private javax.swing.JLabel Avatar3;
    private javax.swing.JLabel Avatar4;
    private javax.swing.JPanel apostar10;
    private javax.swing.JPanel apostar100;
    private javax.swing.JPanel apostar25;
    private javax.swing.JPanel apostar5;
    private javax.swing.JPanel apostar50;
    private javax.swing.JPanel btnPasar;
    private javax.swing.JPanel btnSalir;
    private javax.swing.JPanel btnTirarDados;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JLabel labelPlayer1;
    private javax.swing.JLabel labelPlayer2;
    private javax.swing.JLabel labelPlayer3;
    private javax.swing.JLabel labelPlayer4;
    private javax.swing.JPanel panelPlayer1;
    private javax.swing.JPanel panelPlayer2;
    private javax.swing.JPanel panelPlayer3;
    private javax.swing.JPanel panelPlayer4;
    private javax.swing.JLabel tableroFondo;
    private javax.swing.JLabel txtSalir;
    // End of variables declaration//GEN-END:variables
}
